# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foldl_list": "list.ipynb",
         "A": "list.ipynb",
         "B": "list.ipynb",
         "foldr_list": "list.ipynb"}

modules = ["pycollections/list.py"]

doc_url = "https://choct155.github.io/pyutils/"

git_url = "https://github.com/choct155/pyutils/tree/master/"

def custom_doc_links(name): return None
